name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  # Job 1: Run Tests
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and test with Docker Compose
        run: |
          docker compose -f "Task 1/app/compose.yaml" build tests
          docker compose -f "Task 1/app/compose.yaml" run tests
          # Job 1: Run Tests
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and test with Docker Compose
        run: |
          docker compose -f "Task 1/app/compose.yaml" build app
          docker compose -f "Task 1/app/compose.yaml" run app

  deploy:
    needs: [tests, build] # Only run if tests pass
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate Docker with GCP
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/todo-app:$GITHUB_SHA .

      - name: Push Docker image to Google Container Registry
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/todo-app:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy todo-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/todo-app:$GITHUB_SHA \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
