name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  # Job 1: Run Tests
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and test with Docker Compose
        run: |
          docker compose -f "Task 1/app/compose.yaml" build tests
          docker compose -f "Task 1/app/compose.yaml" run tests

  build-and-push:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v1 # google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Authenticate Docker with GCP
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push `app` service Docker image
        run: |
          docker compose -f "Task 1/app/compose.yaml" build app
          IMAGE_ID=$(docker images --filter=reference='*app*' --format "{{.ID}}")
          docker tag $IMAGE_ID "${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPOSITORY }}/todo-app-image:latest"
          docker push "${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPOSITORY }}/todo-app-image:latest"

      - name: Build and push `mongo` service Docker image
        run: |
          docker pull mongo:latest
          docker tag mongo ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPOSITORY }}/todo-mongo-image:latest
          docker push ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPOSITORY }}/todo-mongo-image:latest

  # Job 3: Deploy to Google Cloud Run
  deploy-app:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v1 # google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy `mongo` service to Cloud Run
        run: |
          gcloud run deploy todo-mongo \
          --image="${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPOSITORY }}/todo-mongo-image:${{ github.sha }}" \
          --platform managed \
          --region ${{ secrets.REGION }} \
          --allow-unauthenticated \
          --port 27017

      - name: Deploy `app` service to Cloud Run
        run: |
          gcloud run deploy todo-app \
            --image="${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPOSITORY }}/todo-app-image:${{ github.sha }}" \
            --platform managed \
            --region ${{ secrets.REGION }} \
            --allow-unauthenticated \
            --port 3000
